# Generated by Django 4.2 on 2023-05-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash')], max_length=6)),
                ('category', models.CharField(choices=[('food', 'Food & Drinks'), ('shopping', 'Shopping'), ('transport', 'Transport')], max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
