# Generated by Django 4.2 on 2023-05-05 18:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Drinks'), ('shopping', 'Shopping'), ('transport', 'Transport'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('comm', 'Communication'), ('meds', 'Meds'), ('stationary', 'Stationary'), ('personal', 'Personal'), ('edun', 'Education'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('DCard', 'Debit Card'), ('CCard', 'Credit Card')], max_length=6),
        ),
        migrations.AlterField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
