# Generated by Django 4.2 on 2023-06-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_expense_category_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='balence',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
