# Generated by Django 4.2 on 2023-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_expense_balence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='balence',
        ),
        migrations.AddField(
            model_name='profile',
            name='balence',
            field=models.IntegerField(default=0),
        ),
    ]
